# Generated by Django 3.1.2 on 2020-10-31 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField()),
                ('teamsamount', models.IntegerField()),
                ('dateofstart', models.DateTimeField(verbose_name='Дата начала турнира')),
            ],
        ),
        migrations.CreateModel(
            name='Typesoftour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип турнира')),
            ],
        ),
        migrations.CreateModel(
            name='Tourteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player', verbose_name='Капитан')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tournament', verbose_name='Турнир')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.typesoftour', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalsteamone', models.PositiveIntegerField(default=0)),
                ('goalsteamtwo', models.PositiveIntegerField(default=0)),
                ('dateofstart', models.DateTimeField()),
                ('teamone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstteam', to='mainapp.team', verbose_name='Первая команда')),
                ('teamtwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondteam', to='mainapp.team', verbose_name='Вторая команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tournament', verbose_name='Турнир')),
            ],
        ),
    ]
