# Generated by Django 3.1.2 on 2020-11-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finishedtour',
            field=models.BooleanField(default=False),
        ),
    ]
