# Generated by Django 3.1.2 on 2020-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_tournament_islive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.CharField(default=1, max_length=255, verbose_name='Город проведения'),
            preserve_default=False,
        ),
    ]
