# Generated by Django 3.1.2 on 2020-11-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201109_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
