# Generated by Django 3.1.2 on 2020-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20201114_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, default='blankuser.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='dateofstart',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, default='cup.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teamsamount',
            field=models.IntegerField(blank=True),
        ),
    ]
